dbtVersion: 1.6.3

jobs:
 - name: identify duplicate customers
   schedule:
      - '0 */4 * * 1-5'
      - 30 2 * * 6-7 # weekends at 2.30 am
      - 30 14 * * 6-7 # weekends at 2.30 pm
   steps:
     - name: run dup_cust model
       command: dbt run --select +duplicate_customers